# -*- coding: UTF-8 -*-
import socket

DEFAULT_CLIENT_PORT = 25566
DEFAULT_PORT = 25565
DEFAULT_CONNECT_POOL_SIZE = 5
DEFAULT_BUFFER = 1024
DEFAULT_INET = socket.AF_INET
DEFAULT_STREAM = socket.SOCK_STREAM

DEFAULT_UPLOAD_PATH = "upload"
DEFAULT_IMAGE_UPLOAD_PATH = "upload/img"
