# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netprotoc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnetprotoc.proto\x12\tNetProtoc\"\xfc\x02\n\x08Protocol\x12(\n\x06method\x18\x01 \x01(\x0e\x32\x18.NetProtoc.ConnectMethod\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.NetProtoc.ConnectType\x12)\n\tfile_type\x18\x04 \x01(\x0e\x32\x16.NetProtoc.ConnectFile\x12\x11\n\temergency\x18\x05 \x01(\x08\x12+\n\x04\x62its\x18\n \x03(\x0b\x32\x1d.NetProtoc.Protocol.BitsEntry\x12-\n\x05pairs\x18\x0b \x03(\x0b\x32\x1e.NetProtoc.Protocol.PairsEntry\x12\x1d\n\x15millisecond_timestamp\x18\x0e \x01(\r\x12\x0c\n\x04strs\x18\x0f \x03(\t\x1a+\n\tBitsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a,\n\nPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*N\n\rConnectMethod\x12\t\n\x05LOGIN\x10\x00\x12\x0c\n\x08REGISTER\x10\x01\x12\x0b\n\x07MESSAGE\x10\x03\x12\x0c\n\x08\x43ONTRACT\x10\x04\x12\t\n\x05\x43LOSE\x10\x05*5\n\x0b\x43onnectType\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x12\x0b\n\x07TRANSIT\x10\x02*+\n\x0b\x43onnectFile\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\x07\n\x03\x42IN\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netprotoc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCOL_BITSENTRY._options = None
  _PROTOCOL_BITSENTRY._serialized_options = b'8\001'
  _PROTOCOL_PAIRSENTRY._options = None
  _PROTOCOL_PAIRSENTRY._serialized_options = b'8\001'
  _CONNECTMETHOD._serialized_start=413
  _CONNECTMETHOD._serialized_end=491
  _CONNECTTYPE._serialized_start=493
  _CONNECTTYPE._serialized_end=546
  _CONNECTFILE._serialized_start=548
  _CONNECTFILE._serialized_end=591
  _PROTOCOL._serialized_start=31
  _PROTOCOL._serialized_end=411
  _PROTOCOL_BITSENTRY._serialized_start=322
  _PROTOCOL_BITSENTRY._serialized_end=365
  _PROTOCOL_PAIRSENTRY._serialized_start=367
  _PROTOCOL_PAIRSENTRY._serialized_end=411
# @@protoc_insertion_point(module_scope)
